%**************************************************************************
% classify_demand.m
% function [           ...
% out_T,               ...
% out_dpw              ...
% ] = classify_demand( ...
%     in_demandcoord,  ...
%     in_weight,       ...
%     in_pointcoord    ...
%     )
%**************************************************************************

function [           ...
out_T,               ...
out_dpw              ...
] = classify_demand( ...
    in_demandcoord,  ...
    in_weight,       ...
    in_pointcoord    ...
    )

szp = size(in_pointcoord, 1);
u = 1:szp;
out_T = knnclassify(in_demandcoord, in_pointcoord, u);
out_dpw = zeros(szp, 1);
for k = u, out_dpw(k) = sum(in_weight(out_T == k)); end
end
%**************************************************************************