%**************************************************************************
% cluster_demand.m
% function [          ...
% out_dpc             ...
% ] = cluster_demand( ...
%     in_demandcoord, ...
%     in_maxclust,    ...
%     in_linkage,     ...
%     in_snap         ...
%     )
%**************************************************************************

function [          ...
out_dpc             ...
] = cluster_demand( ...
    in_demandcoord, ...
    in_maxclust,    ...
    in_linkage,     ...
    in_snap         ...
    )

switch lower(in_linkage)
case 'kmeans'
    T = kmeans(in_demandcoord, in_maxclust);
otherwise
    T = clusterdata(in_demandcoord,          ...
                    'maxclust', in_maxclust, ...
                    'linkage',  in_linkage);
end

szp = max(T);
out_dpc = zeros(szp, 2);

for k = 1:szp
    sel = T == k;
    demand = in_demandcoord(sel, :);
    point = [sum(demand(:, 1)), sum(demand(:, 2))] ./ sum(sel);
    if (in_snap), point = demand(knnsearch(demand, point), :); end
    out_dpc(k, :) = point;
end
end
%**************************************************************************