%**************************************************************************
% conn_mysql.m
% function [      ...
% out_conn        ...
% ] = conn_mysql( ...
%     in_dbhost,  ...
%     in_dbport,  ...
%     in_dbname,  ...
%     in_dbuser,  ...
%     in_dbpass   ...
%     )
%**************************************************************************

function [      ...
out_conn        ...
] = conn_mysql( ...
    in_dbhost,  ...
    in_dbport,  ...
    in_dbname,  ...
    in_dbuser,  ...
    in_dbpass   ...
    )

driver = 'com.mysql.jdbc.Driver';
dburl = ['jdbc:mysql://' in_dbhost ':' in_dbport '/' in_dbname];
out_conn = database(in_dbname, in_dbuser, in_dbpass, driver, dburl);
if (~isempty(out_conn.Message)), error(out_conn.Message); end
end
%**************************************************************************