%**************************************************************************
% filter_demand_by_weekday.m
% function [                    ...
% out_sel                       ...
% ] = filter_demand_by_weekday( ...
%     in_demand,                ...
%     in_wday                   ...
%     )
%**************************************************************************

function [                    ...
out_sel                       ...
] = filter_demand_by_weekday( ...
    in_demand,                ...
    in_wday                   ...
    )

out_sel = strcmpi(in_wday, in_demand);
end
%**************************************************************************