%**************************************************************************
% filter_demand_by_priority.m
% function [                     ...
% out_sel                        ...
% ] = filter_demand_by_priority( ...
%     in_demand,                 ...
%     in_priority                ...
% 	  )
%**************************************************************************

function [                     ...
out_sel                        ...
] = filter_demand_by_priority( ...
	in_demand,                 ...
	in_priority                ...
	)

out_sel = cell2mat(in_demand) == in_priority;
end
%**************************************************************************