%**************************************************************************
% get_demand.m
% function [ ...
% out_data   ...
% ] = get_demand()
%**************************************************************************

function [ ...
out_data   ...
] = get_demand()

global CONFIG

dbuser  = CONFIG.MAINDBUSER;
dbpass  = CONFIG.MAINDBPASSWORD;
dbhost  = CONFIG.MAINDBHOST;
dbport  = CONFIG.MAINDBPORT;
dbname  = CONFIG.MAINDBNAME;
dbtable = CONFIG.MAINDBDEMANDTABLE;
dbmax   = CONFIG.MAINDBDEMANDMAXROWS;

conn = conn_mysql(dbhost, dbport, dbname, dbuser, dbpass);
dtor = onCleanup(@()close(conn));

selq = [
	'select'               ' ' ...
    'id'                   ',' ...
    'latitud'              ',' ...
    'longitud'             ',' ...
    'fecha'                ',' ...
    'dia_semana'           ',' ...
    'hora_llamada'         ',' ...
    'vprioridad'           ' ' ...
    'from ' dbtable        ' ' ...
    'where'                ' ' ...
    'latitud is not null'  ' ' ...
    'and'                  ' ' ...
    'longitud is not null'     ...
];

curs = exec(conn, selq);
if (~isempty(curs.Message)), error(curs.Message); end

data = fetch(curs, dbmax);
data = data.Data;

if (numel(data) < 7)
    out_data = [];
else
    sel = polygon_test(cell2mat([data(:, 2), data(:, 3)]));
    out_data = data(sel, :);
end
end
%**************************************************************************