%**************************************************************************
% polygon_test.m
% function [        ...
% out_sel           ...
% ] = polygon_test( ...
%     in_coord      ...
%     )
%**************************************************************************

function [        ...
out_sel           ...
] = polygon_test( ...
    in_coord      ...
    )

global CONFIG

bp = CONFIG.MAINBOUNDINGPOLY;

out_sel = inpolygon(in_coord(:, 2), in_coord(:, 1), bp(:, 2), bp(:, 1));
end
%**************************************************************************